import { Geist, Geist_Mono } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap-icons/font/bootstrap-icons.css';
import "./globals.css";
import AuthHydrator from "./components/AuthHydrator";

import LoadScriptOnRouteChange from "./components/LoadScriptOnRouteChange";
import BootstrapClient from "./components/BootstrapClient";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Pravasi Mitra",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700" rel="stylesheet" />

  <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet" />
{/*   <link rel="stylesheet" href="/assets/css/bootstrap.min.css" /> */}
  <link rel="stylesheet" href="/assets/css/plugins.css" />
  <link rel="stylesheet" href="/assets/css/style.css" />
  <link rel="stylesheet" href="/assets/css/tm-customizer.css" />
  <link rel="stylesheet" href="/assets/css/custom.css" />

<link rel="icon" href="/assets/images/logo/logo-dark.png" />

  </head>
  <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
<div id="wrapper" className="wrapper">
{/*   <div className="tm-preloader">
  <span className="tm-preloader-box" />
  </div> */}
<AuthHydrator />
  {children}

  </div>
{/*   <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBgwgIuDRkO7HlxvpWN-vPePnGVWss5r5g"></script> */}

<BootstrapClient />
  <LoadScriptOnRouteChange />
  </body>
  </html>
  );
}
